/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context } from "./../graphql/context"
import { FieldAuthorizeResolver } from "nexus/dist/plugins/fieldAuthorizePlugin"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    datetime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    datetime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SignInInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  SignUpInput: { // input type
    birthDate: string; // String!
    email: string; // String!
    gender: NexusGenEnums['Gender']; // Gender!
    name: string; // String!
    password: string; // String!
    weight: number; // Float!
  }
}

export interface NexusGenEnums {
  Gender: "FEMALE" | "MALE"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AccessToken: { // root type
    accessToken?: string | null; // String
  }
  Consumption: { // root type
    id?: string | null; // ID
    time?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Drink: { // root type
    id?: string | null; // ID
    name?: string | null; // String
    percentage?: number | null; // Float
    volume?: number | null; // Float
  }
  Mutation: {};
  Participant: { // root type
    joinedDate?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Query: {};
  Session: { // root type
    code?: string | null; // String
    id?: string | null; // ID
    name?: string | null; // String
  }
  User: { // root type
    birthDate?: NexusGenScalars['DateTime'] | null; // DateTime
    email?: string | null; // String
    gender?: NexusGenEnums['Gender'] | null; // Gender
    id?: string | null; // ID
    name?: string | null; // String
    weight?: number | null; // Float
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AccessToken: { // field return type
    accessToken: string | null; // String
  }
  Consumption: { // field return type
    drink: NexusGenRootTypes['Drink'] | null; // Drink
    id: string | null; // ID
    time: NexusGenScalars['DateTime'] | null; // DateTime
  }
  Drink: { // field return type
    id: string | null; // ID
    name: string | null; // String
    percentage: number | null; // Float
    volume: number | null; // Float
  }
  Mutation: { // field return type
    signIn: boolean | null; // Boolean
    signOut: boolean | null; // Boolean
    signUp: boolean | null; // Boolean
  }
  Participant: { // field return type
    consumptions: Array<NexusGenRootTypes['Consumption'] | null> | null; // [Consumption]
    currentBAC: number | null; // Float
    joinedDate: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    allConsumptions: Array<NexusGenRootTypes['Consumption'] | null> | null; // [Consumption]
    allDrinks: Array<NexusGenRootTypes['Drink'] | null> | null; // [Drink]
    allUsers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    me: NexusGenRootTypes['User'] | null; // User
    mySessions: Array<NexusGenRootTypes['Session'] | null> | null; // [Session]
  }
  Session: { // field return type
    code: string | null; // String
    id: string | null; // ID
    name: string | null; // String
    owner: NexusGenRootTypes['User'] | null; // User
    participants: Array<NexusGenRootTypes['Participant'] | null> | null; // [Participant]
  }
  User: { // field return type
    birthDate: NexusGenScalars['DateTime'] | null; // DateTime
    email: string | null; // String
    gender: NexusGenEnums['Gender'] | null; // Gender
    id: string | null; // ID
    name: string | null; // String
    weight: number | null; // Float
  }
}

export interface NexusGenFieldTypeNames {
  AccessToken: { // field return type name
    accessToken: 'String'
  }
  Consumption: { // field return type name
    drink: 'Drink'
    id: 'ID'
    time: 'DateTime'
  }
  Drink: { // field return type name
    id: 'ID'
    name: 'String'
    percentage: 'Float'
    volume: 'Float'
  }
  Mutation: { // field return type name
    signIn: 'Boolean'
    signOut: 'Boolean'
    signUp: 'Boolean'
  }
  Participant: { // field return type name
    consumptions: 'Consumption'
    currentBAC: 'Float'
    joinedDate: 'DateTime'
    user: 'User'
  }
  Query: { // field return type name
    allConsumptions: 'Consumption'
    allDrinks: 'Drink'
    allUsers: 'User'
    me: 'User'
    mySessions: 'Session'
  }
  Session: { // field return type name
    code: 'String'
    id: 'ID'
    name: 'String'
    owner: 'User'
    participants: 'Participant'
  }
  User: { // field return type name
    birthDate: 'DateTime'
    email: 'String'
    gender: 'Gender'
    id: 'ID'
    name: 'String'
    weight: 'Float'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    signIn: { // args
      credentials: NexusGenInputs['SignInInput']; // SignInInput!
    }
    signUp: { // args
      user: NexusGenInputs['SignUpInput']; // SignUpInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Authorization for an individual field. Returning "true"
     * or "Promise<true>" means the field can be accessed.
     * Returning "false" or "Promise<false>" will respond
     * with a "Not Authorized" error for the field.
     * Returning or throwing an error will also prevent the
     * resolver from executing.
     */
    authorize?: FieldAuthorizeResolver<TypeName, FieldName>
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}